### PR TITLE
Made codebase easier to maintain (and added mwv: URIs)

### PR DESCRIPTION
**Pull request by YourOrdinaryCat**
- Data now uses ViewModels and binding
- Layouts now use grids and stacks instead of being hardcoded through margins
- Performance and startup speeds are better now
- You can now open pages with `mwv:` (about, links, system, theme)

### CODE REVIEW

**Comment by Erisa** [comment]
Hi.

I would like to set aside any ties I may have to this software for the moment, and speak personally and from the heart.

I say these words not as a collaborator or as a friend, but as a hobbyist developer in a similar situation.

A lot of the work done here is admirable, and I dread to think how much time would have been spent on all of it.
However, I feel like it is too much. What I am looking at here is essentially a rewrite of someone's codebase to meet the standards and beliefs of another, with a number of wide-spreading improvements thrown in.
While this is perfectly fine and allowed under GitHubs rules, I do not see how it could possibly be merged.

If I think hypothetically for a moment how I would feel seeing this kind of PR against my personal project, something I have put a lot of time and effort into, it would discourage me immensely. All that work and energy, all that labour of love. All to be superceded by someone's rewrite. The project wouldn't even be distinquishable anymore, it wouldn't be mine. I would just be taking credit for someone else's work that began as a deriviative of mine. It would feel wrong, and what point would there be in making modifications further? Clearly there is someone else who knows better now, and my work would have been reduced to nothing but a remote inspiration

And from a maintaining standpoint: this PR is completely unreviewable. There is no concievable way to ever review a list of changes this big. The time and energy required is so immense it could have been spent creating a number of other projects and features, or many other things one might prefer to do with their time. It is simply too much at worse, and in my personal opinion (Not speaking on behalf of this project) it simply cannot be done.

A better approach to this kind of problem would have been to create Issues for the things that need improving, and send incremental PRs over time to resolve them, in a reviewable form with concise documentation of what has been changed and what it affects.

I do not mean any ill will whatsoever and I have respect for the energy you have put into your derivative of this project, I just feel something needed to be said about the state of this PR, personally and from the heart.

**Comment by YourOrdinaryCat** [comment]
That's fair. I'll close this and maintain my fork for now then.

**Comment by YourOrdinaryCat** [comment]
Would the mwv: URIs be useful at least? The README said it was planned, so I can probably add those in a separate branch and make a PR for that. Sorry if this seemed pretentious, I was just really interested in the project and wanted to improve a few things, but I ended up rewriting most of it to make it easier to work with, thought it would be helpful but if you put it that way I can see how it can be an issue.

**Comment by torchgm** [comment]
Hi! Just wanted to throw my thoughts in on the matter; I really appreciate your interest and commitment to the project, and it never came across as pretentious or anything though Erisa is right, it has been rather disheartening to approach for me personally.

I write code as a hobby, as a learning exercise, and as a coping mechanism - it's one of the few things that keeps me feeling as though I've been vaguely productive. I know a lot of my code is really rather crap, but  I try my best to make sure that the end product at least works. When I saw this PR, I was thrown into a bit of a dilemma - on one hand, I like the fact that it's my little thing that I'm working on, and having someone basically rewrite everything better just entirely puts me off ever working on it. However on the other hand, I'd feel really bad for rejecting all this genuine hard work you've put into it because you care about the project.

Unfortunately I'll probably continue to write relatively unmaintainable-for-most code because that's sorta what happens when you're self-taught and only really write things for yourself apparently (I get lost staring at any reasonable amount of code that isn't mine), but  I'd be more than happy to implement little tweaks and changes here and there.

I really don't want this to come across as some kind of selfish "this is *my* project don't you dare try to help me" or "my code is better than yours" or anything, and I'm honestly taken aback by the amount of effort and devotion you've put into my dumb little project, it means a lot that people would care that much! So I hope this all makes sense and that you understand I didn't merge it out of stubbornness or jealousy or anything, I'm just not really kitted out to deal with such significant contributions.

As for the URIs however, it was certainly something I wanted to look into but also haven't had the time or motivation to recently, so feel free to submit a PR for them if you still wish to and I'll get right on top of reviewing it!

**Comment by YourOrdinaryCat** [comment]
That's fine, I should've split up the PR a little at least. It's way too big and I'm still not very good at doing them. I will try working on the URIs in a bit, although I don't have much time to do it right now. Really sorry if this has been disheartening or has hurt anyone in any way, I should've taken the hint after having this open for so long and bloating the PR like it's nothing. Have a good day.

**Comment by torchgm** [comment]
There's no need to apologise! I totally understand you were just trying to help and I really appreciate that. As for the URIs, no rush of course! Thanks for your contributions regardless, and I hope you have a good day too ^^

**Pull request closed without merging**
